import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, Check, Clock3, MapPin, Phone, ShieldCheck, Star } from 'lucide-react'
import { PageShell, Reviews, SectionCta, ServiceCard, TrustStrip } from '@/components/site'
import { imageRoot } from '@/lib/site-data'
const featured=[{slug:'standard-porta-potty',name:'Standard Porta Potty',image:'outdoor-porta-potties.jpg',blurb:'Clean, dependable units for construction sites and everyday needs.'},{slug:'deluxe-portable-restroom',name:'Deluxe Portable Restroom',image:'deluxe-porta-potty.png',blurb:'A better guest experience with roomier interiors and premium finishes.'},{slug:'ada-accessible-restroom',name:'ADA Accessible Restroom',image:'ada-porta-potty.png',blurb:'Comfortable, compliant access for every guest and worksite.'},{slug:'luxury-restroom-trailer',name:'Luxury Restroom Trailer',image:'luxury-trailer.png',blurb:'Upscale restroom trailers for weddings and galas.'},{slug:'construction-site-toilets',name:'Construction Site Toilets',image:'construction-toilet-portable.jpg',blurb:'Reliable jobsite service that keeps crews moving.'},{slug:'event-portable-restrooms',name:'Event Portable Restrooms',image:'event-porta-potty-rentals.jpg',blurb:'Polished units for events of every size.'}]

export default function Home() { return <PageShell><section className="hero"><div className="hero-copy"><span className="eyebrow">Local portable restroom rentals</span><h1>Clean restrooms.<br /><em>Zero headaches.</em></h1><p>Reliable portable toilets delivered across Boynton Beach and Palm Beach County. For worksites, weddings, parties, and everything in between.</p><div className="hero-actions"><Link href="/contact" className="button">Get my free quote <ArrowRight size={17} /></Link><a href="tel:+17283007030" className="button button-outline"><Phone size={17} /> (728) 300-7030</a></div><div className="hero-proof"><span className="stars">★★★★★</span><span><strong>5.0 local rating</strong><small>Trusted by homes, crews & events</small></span></div></div><div className="hero-visual"><Image src={imageRoot+'outdoor-porta-potties.jpg'} alt="Clean portable restrooms ready for delivery in Boynton Beach" fill priority sizes="(max-width: 800px) 100vw, 50vw" /><div className="hero-float"><span className="float-icon"><Check /></span><span><strong>On-time delivery</strong><small>We show up when we say we will.</small></span></div></div></section><TrustStrip/><section className="section services-preview"><div className="section-heading"><div><span className="eyebrow">The right fit for your plans</span><h2>Restroom rentals<br /><span>without the runaround.</span></h2></div><Link className="text-link" href="/services">View all services <ArrowRight size={17} /></Link></div><div className="service-grid">{featured.map(s=><ServiceCard key={s.slug} service={s}/>)}</div></section><section className="split-section"><div className="split-image"><Image src={imageRoot+'about-us.jpg'} alt="Boynton Beach Restroom Logistics team equipment" fill sizes="(max-width: 800px) 100vw, 50vw" /></div><div className="split-copy"><span className="eyebrow">Your neighbors in logistics</span><h2>Professional where it matters. <span>Personal where it counts.</span></h2><p>We are a local team that believes the little things make the biggest difference: clean equipment, clear communication, and a delivery that fits your site.</p><ul className="check-list"><li><ShieldCheck /> Cleaned and inspected before every drop</li><li><Clock3 /> Same-day and recurring service options</li><li><MapPin /> Proudly serving Palm Beach County</li></ul><Link href="/about" className="text-link">Meet the local team <ArrowRight size={17}/></Link></div></section><Reviews/><SectionCta/></PageShell> }

export const metadata = { title: 'Portable Toilet Rental in Boynton Beach, FL | Restroom Logistics', description: 'Clean, reliable porta potty rentals for construction sites, events, homes, and emergencies in Boynton Beach and Palm Beach County.' }
