'use client'
import Link from 'next/link'
import Image from 'next/image'
import { useState } from 'react'
import { ArrowRight, Check, ChevronDown, Menu, Phone, ShieldCheck, X, Zap } from 'lucide-react'
import { imageRoot, services } from '@/lib/site-data'

export { imageRoot, services }


const reviews=[{quote:'They answered on the first call, delivered exactly when promised, and the unit was spotless.',name:'Jordan M.',role:'General contractor, Boynton Beach'},{quote:'Our wedding guests noticed how clean and nice everything was. The whole process felt easy.',name:'Emily R.',role:'Event host, Lake Worth'},{quote:'Best local rental team we have used. Fast communication, fair pricing, and no surprises.',name:'Carlos T.',role:'Property manager, Delray Beach'}]
export function Header(){const[open,setOpen]=useState(false);const[drop,setDrop]=useState(false);return <><div className="announcement"><Zap size={14}/> Same-day delivery across Palm Beach County <a href="tel:+17283007030">Call (728) 300-7030</a></div><header className="site-header"><Link href="/" className="brand" onClick={()=>setOpen(false)}><span className="brand-mark">BL</span><span>Boynton Beach<br/><strong>Restroom Logistics</strong></span></Link><button className="menu-button" aria-label="Open navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={`main-nav ${open?'is-open':''}`}><Link href="/">Home</Link><div className="services-nav" onMouseEnter={()=>setDrop(true)} onMouseLeave={()=>setDrop(false)}><button onClick={()=>setDrop(!drop)}>Services <ChevronDown size={15}/></button>{drop&&<div className="services-dropdown">{services.map(s=><Link key={s.slug} href={`/services/${s.slug}`}>{s.name}</Link>)}</div>}</div><Link href="/emergency">24/7 Emergency</Link><Link href="/about">Why Us</Link><Link href="/blog">Blog</Link><Link href="/contact">Contact</Link><a className="nav-phone" href="tel:+17283007030"><Phone size={16}/> (728) 300-7030</a></nav></header></>}
export function Footer(){return <footer><div className="footer-grid"><div><Link href="/" className="brand footer-brand"><span className="brand-mark">BL</span><span>Boynton Beach<br/><strong>Restroom Logistics</strong></span></Link><p>Clean, dependable portable restroom rentals delivered with local care across Palm Beach County.</p></div><div><h4>Explore</h4><Link href="/services">All services</Link><Link href="/about">Why choose us</Link><Link href="/blog">Helpful guides</Link></div><div><h4>Get in touch</h4><a href="tel:+17283007030">(728) 300-7030</a><a href="mailto:contact@boyntonbeachportapotty.com">contact@boyntonbeachportapotty.com</a><span>1500 Gateway Blvd<br/>Boynton Beach, FL 33426</span></div></div><div className="footer-bottom"><span>© 2026 Boynton Beach Restroom Logistics</span><span>Serving Boynton Beach · Delray Beach · Lake Worth · Boca Raton</span></div></footer>}
export function Reviews(){return <section className="reviews-section"><div className="section-heading"><div><span className="eyebrow">Local people. Real reviews.</span><h2>Service that leaves a good impression.</h2></div><div className="rating"><strong>5.0</strong><span><span className="stars">★★★★★</span><small>Based on local customer reviews</small></span></div></div><div className="reviews-grid">{reviews.map(r=><article className="review-card" key={r.name}><span className="stars">★★★★★</span><p>“{r.quote}”</p><strong>{r.name}</strong><small>{r.role}</small></article>)}</div></section>}
export function PageShell({children}:{children:React.ReactNode}){return <><Header/><main>{children}</main><a className="floating-call" href="tel:+17283007030"><Phone size={18}/><span>Need a restroom?</span> Call now</a><Footer/></>}
export function ServiceCard({service}:{service:typeof services[number]}){return <Link href={`/services/${service.slug}`} className="service-card"><div className="service-image"><Image src={imageRoot+service.image} alt={service.name} fill sizes="(max-width:700px) 100vw, 33vw"/></div><div className="service-card-body"><h3>{service.name}</h3><p>{service.blurb}</p><span className="text-link">Explore service <ArrowRight size={16}/></span></div></Link>}
export function TrustStrip(){return <div className="trust-strip"><span><ShieldCheck size={20}/> Cleaned before every delivery</span><span><Check size={20}/> Clear, upfront pricing</span><span><Phone size={20}/> Local team, real answers</span></div>}
export function SectionCta(){return <section className="cta-band"><div><span className="eyebrow">Ready when you are</span><h2>Let’s make the restroom part easy.</h2><p>Tell us what you’re planning and we’ll recommend the right setup.</p></div><Link className="button button-light" href="/contact">Get a fast quote <ArrowRight size={17}/></Link></section>}
